#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
MOUNTS_DIR="${1:-$ROOT_DIR/configs/mounts}"
OUTPUT_FILE="${2:-$ROOT_DIR/configs/generated/docker-compose.mounts.yml}"

mkdir -p "$(dirname "$OUTPUT_FILE")"

MOUNTS_DIR="$MOUNTS_DIR" OUTPUT_FILE="$OUTPUT_FILE" node --input-type=module <<'EOF'
import fs from "node:fs";
import path from "node:path";

const mountsDir = path.resolve(process.env.MOUNTS_DIR);
const outputFile = path.resolve(process.env.OUTPUT_FILE);

function fail(message) {
  console.error(`[mounts] ${message}`);
  process.exit(1);
}

function yamlString(value) {
  return JSON.stringify(value);
}

function readMountFiles(dir) {
  if (!fs.existsSync(dir)) {
    return [];
  }
  return fs.readdirSync(dir)
    .filter((item) => item.endsWith(".json") && !item.endsWith(".example.json"))
    .sort()
    .map((item) => path.join(dir, item));
}

function validateName(name, source) {
  if (typeof name !== "string" || name.trim() === "") {
    fail(`${source}: name is required`);
  }
  const normalized = name.trim();
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(normalized) || normalized === "." || normalized === "..") {
    fail(`${source}: invalid name=${JSON.stringify(name)}`);
  }
  return normalized;
}

function validateHostPath(hostPath, source) {
  if (typeof hostPath !== "string" || hostPath.trim() === "") {
    fail(`${source}: hostPath is required`);
  }
  const normalized = hostPath.trim();
  if (!path.isAbsolute(normalized)) {
    fail(`${source}: hostPath must be an absolute path`);
  }
  return normalized;
}

function validateReadOnly(value, source) {
  if (value == null) {
    return false;
  }
  if (typeof value !== "boolean") {
    fail(`${source}: readOnly must be a boolean`);
  }
  return value;
}

function validateKind(value, source) {
  if (value == null || value === "") {
    return "directory";
  }
  if (value !== "directory" && value !== "socket") {
    fail(`${source}: kind must be "directory" or "socket"`);
  }
  return value;
}

const mountFiles = readMountFiles(mountsDir);
const seenNames = new Set();
const volumeEntries = [];

for (const filePath of mountFiles) {
  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (error) {
    fail(`${filePath}: failed to parse JSON: ${error instanceof Error ? error.message : String(error)}`);
  }

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    fail(`${filePath}: mount config must be a JSON object`);
  }

  const name = validateName(parsed.name, filePath);
  if (seenNames.has(name)) {
    fail(`${filePath}: duplicate name=${JSON.stringify(name)}`);
  }
  seenNames.add(name);

  const hostPath = validateHostPath(parsed.hostPath, filePath);
  const readOnly = validateReadOnly(parsed.readOnly, filePath);
  const kind = validateKind(parsed.kind, filePath);

  let stat;
  try {
    stat = fs.statSync(hostPath);
  } catch (_error) {
    fail(`${filePath}: hostPath does not exist: ${hostPath}`);
  }

  let targetPath;
  if (kind === "directory") {
    if (!stat.isDirectory()) {
      fail(`${filePath}: directory mount requires an existing directory: ${hostPath}`);
    }
    targetPath = `/workspace/${name}`;
  } else {
    targetPath = hostPath;
  }

  const suffix = readOnly ? ":ro" : "";
  volumeEntries.push(`${hostPath}:${targetPath}${suffix}`);
}

const lines = [
  "# Generated by scripts/docker/generate-mount-compose.sh",
  "services:",
  "  backend:"
];

if (volumeEntries.length === 0) {
  lines.push("    {}");
} else {
  lines.push("    volumes:");
  for (const entry of volumeEntries) {
    lines.push(`      - ${yamlString(entry)}`);
  }
}

fs.writeFileSync(outputFile, `${lines.join("\n")}\n`);
console.log(`[mounts] wrote ${outputFile} (${volumeEntries.length} mount${volumeEntries.length === 1 ? "" : "s"})`);
EOF
